<a href="https://colab.research.google.com/github/Vishal9199/SmartBridge-Externship-ADS/blob/main/GCC_LAB_1_Exrernship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ASSIGNMENT **1**





1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [11]:
name = "Vishal Kumar Mahatha"
age = 20

print("Name:", name)
print("Age:", age)

Name: Vishal Kumar Mahatha
Age: 20


2. X="Datascience is used to extract meaningful insights." Split the string

In [12]:
X = "Datascience is used to extract meaningful insights."
words = X.split()

print(words)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


3. Make a function that gives multiplication of two numbers

In [13]:
def multiply_numbers(a, b):
    return a * b

result = multiply_numbers(4, 5)
print("Multiplication Result:", result)

Multiplication Result: 20


4. Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [14]:
states_capitals = {
    'California': 'Sacramento',
    'Texas': 'Austin',
    'Florida': 'Tallahassee',
    'New York': 'Albany',
    'Illinois': 'Springfield'
}

print("States and Capitals:")
for state, capital in states_capitals.items():
    print(state, "-", capital)

States and Capitals:
California - Sacramento
Texas - Austin
Florida - Tallahassee
New York - Albany
Illinois - Springfield


5. Create a list of 1000 numbers using range function.

In [15]:
numbers = list(range(1, 1001))
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

6. Create an identity matrix of dimension 4 by 4.

In [16]:
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


7. Create a 3x3 matrix with values ranging from 1 to 9.

In [17]:
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Create 2 similar dimensional array and perform sum on them.

In [18]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

sum_array = array1 + array2
print(sum_array)

[[ 8 10 12]
 [14 16 18]]


9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive).

In [19]:
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

dates = []
current_date = start_date
while current_date <= end_date:
    dates.append(current_date)
    current_date += timedelta(days=1)

for date in dates:
    print(date)

2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00
2023-02-11 00:00:00
2023-02-12 00:00:00
2023-02-13 00:00:00
2023-02-14 00:00:00
2023-02-15 00:00:00
2023-02-16 00:00:00
2023-02-17 00:00:00
2023-02-18 00:00:00
2023-02-19 00:00:00
2023-02-20 00:00:00
2023-02-21 00:00:00
2023-02-22 00:00:00
2023-02-23 00:00:00
2023-02-24 00:00:00
2023-02-25 00:00:00
2023-02-26 00:00:00
2023-02-27 00:00:00
2023-02-28 00:00:00
2023-03-01 00:00:00


10. Given a dictionary, convert it into corresponding dataframe and display it
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}.

In [20]:
import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
